# aliases for git
alias g='git'
alias gs='git status'
alias gb='git branch'
alias gc='git commit -m'
alias gph='git push'
alias gpl='git pull'
alias gco='git checkout'
alias ga='git add'
alias gl='git log --oneline'
alias grs='git restore --staged'
alias gr='git reset'
alias grhard='git reset --hard'
alias grv='git revert'
alias gmrg='git merge'
alias gcount='git ls-files | xargs wc -l'