# aliases for git
alias g='git'
alias gcl='git clone'
alias gs='git status'
alias gb='git branch'
alias gc='git commit -m'
alias gf='git fetch'
alias gph='git push'
alias gpl='git pull'
alias gco='git checkout'
alias ga='git add'
alias gsh='git stash'
alias gd='git diff'
alias gl='git log --oneline'
alias grs='git restore --staged'
alias gclean='git clean -fd'
alias gr='git reset'
alias grhard='git reset --hard'
alias grv='git revert'
alias gmrg='git merge'
alias gcp='git cherry-pick'
alias gt='git tag'
alias gcount='git ls-files | xargs wc -l'

# other aliases
# gpt.sh should be on your path
alias gpt='gpt.sh -u'
alias gpt4='gpt.sh -m "gpt-4" -u'